name: CI - Tests & Reports

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run unit tests
        run: mvn -B -q clean test

      - name: Generate Surefire & JaCoCo reports
        run: |
          mvn -q surefire-report:report
          mvn -q jacoco:report

      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            target/site/surefire-report.html
            target/site/jacoco/**
